name: "Azion Action Deploy"
description: "This GitHub Action automates the deployment of edge applications on Azion's platform."
inputs:
  applicationName:
    description: "Application Name"
    required: false
  azionPersonalToken:
    description: "Azion Personal Token"
    required: true
  functionArgsFilePath:
    description: "Path function args file ex: args.json" # no commit this file
    required: false
    default: "args.json"
  buildPreset:
    description: "build Preset"
    required: true
  buildMode:
    description: "build Mode"
    required: false
    default: "deliver"
  buildEntry:
    description: "build Entry - if buildMode compute"
    required: false
    default: "./main.js"
  edgeModuleAcceleration:
    description: "enable module acceleration"
    required: false
    default: false
  scriptEnv:
    description: "script environment (stage | production)"
    required: false
    default: "production"  

outputs:
  applicationId:
    description: "Return application id"
  domainUrl:
    description: "Return edge domain url"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: cloud-lightning
  color: orange
